### ISSUE TITLE
Marking form and form controls as invalid?

### ISSUE THREAD

**Issue by pooot** [fergaldoyle/vue-form#10]
I'm using Laravel, and when there are validation errors i want to mark the fields as invalid.

Setting the values manually doesn't trigger any updates...

``` javascript
self.$set('myForm.$valid', false);
self.$set('myForm.$invalid', true);
self.$set('myForm.$submitted', false);
```

Any suggestions?

**Comment by Phunky** [comment]
I've also just come across this, need to set input values as invalid after AJAX Post to server.

**Comment by fergaldoyle** [comment]
You could try something like this:
http://jsfiddle.net/bpc7oyvL/10/

Because validation happens on the server, you'll need to use a custom validator function which has a dynamic condition. It would start off returning `true` (valid) and if the server responds that the field is invalid, you need to make the custom validator return `false` (invalid).  After you switch what is returned by the validator function, you need to tell the field to re-validate itself so that it performs all other internal actions (setting overall form state, adding / removing classes etc.)

You do this by getting a hook into the form, then the form field itself and calling the `validate()` method.

This will only work with latest version, 0.2.4. Also the field has to have a value. Custom validators (like all validators except the required validator) only run if the field has a value.

**Comment by pooot** [comment]
Thanks! Will try it out tomorrow :)

**Comment by fergaldoyle** [comment]
Closing Vue 1 compatible version issues.
