### ISSUE TITLE
Any example to work with a recaptcha?

### ISSUE THREAD

**Issue by sornss** [fergaldoyle/vue-form#120]
I have tried to use vue-form with vue-recaptcha following this https://gist.github.com/ctf0/8037b629ffde02377adeaa43f46863de. But I cannot get it to work. Any working example please?

**Comment by wtho** [comment]
This seems more like a complex conjunction between `vue-recaptcha`, `vue-form` and `laravel` than an issue with `vue-form` itself.

It appears you want to add the captcha component to the form element created by vue-form. For this to work vue-form does not need to be extended or changed, it can probably be done in your Vue component. You can open a new issue once you identified where vue-form should be extended.

You should close this issue here and post your support request e. g. on Stack Overflow instead.

**Comment by sornss** [comment]
@wtho , thank you. I should have raised it to Stack Overflow. Closing the issue for now.
