### ISSUE TITLE
Force validation on every change? (keyup, not blur)

### ISSUE THREAD

**Issue by jezmck** [fergaldoyle/vue-form#86]
Am I right in thinking that, currently, validation only happens on `change` (or perhaps `blur`)?

Can we force validation to happen on keyup (etcetera)?

I'd like a field to "go green" as soon as its content passes validation (e.g. as soon as the input is long enough).

**Comment by fergaldoyle** [comment]
Validation happens when `v-model` updates. You can have real-time `v-model` updates or `onchange` with `v-model.lazy`.

So what you are looking for should be the default behavior. Your styles / messages might be only showing when the field becomes `$dirty`. This only happens after a field is touched, changed and blurred. So you might need to adjust your css rules to not wait for `$dirty`

**Comment by jezmck** [comment]
That's brilliant, thanks.

I had `.lazy` after copying from somewhere, my bad.
